{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "63678f3a-8497-4d8f-8548-8fc521680cd6",
   "metadata": {},
   "source": [
    "### Creation d'un dashbord avec Streamlit"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "dab9bca9-51e8-4054-96dc-38fee668eac6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# dashboard_marketing.py\n",
    "\n",
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import plotly.express as px\n",
    "\n",
    "# --- CONFIGURATION DE LA PAGE ---\n",
    "st.set_page_config(\n",
    "    page_title=\"Dashboard d'Analyse Marketing\",\n",
    "    page_icon=\"📊\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# --- FONCTION DE CHARGEMENT ET NETTOYAGE (AVEC CACHE) ---\n",
    "# Le cache permet de ne pas recharger et nettoyer les données à chaque interaction\n",
    "@st.cache_data\n",
    "def load_and_clean_data(file_path):\n",
    "    \"\"\"Charge les données depuis un fichier CSV et effectue le nettoyage.\"\"\"\n",
    "    data = pd.read_csv(file_path)\n",
    "    \n",
    "    # 1. Supprimer les colonnes entièrement vides\n",
    "    cols_to_drop = [col for col in data.columns if data[col].count() == 0]\n",
    "    data.drop(columns=cols_to_drop, inplace=True)\n",
    "    \n",
    "    # 2. Supprimer les colonnes redondantes\n",
    "    redundant_cols = ['Ads', 'Ad name', 'Delivery level', 'Attribution setting', 'Objective.1', 'Reporting starts', 'Reporting ends']\n",
    "    existing_redundant_cols = [col for col in redundant_cols if col in data.columns]\n",
    "    data.drop(columns=existing_redundant_cols, inplace=True)\n",
    "    \n",
    "    # 3. Remplacer les NaN numériques par 0\n",
    "    numeric_cols = data.select_dtypes(include=np.number).columns\n",
    "    data[numeric_cols] = data[numeric_cols].fillna(0)\n",
    "    \n",
    "    # 4. Conversion des types\n",
    "    data['Day'] = pd.to_datetime(data['Day'])\n",
    "    count_cols = ['Results', 'Reach', 'Impressions', 'Link clicks', 'Clicks (all)', 'Landing page views', 'Content views', 'Website content views']\n",
    "    for col in count_cols:\n",
    "        if col in data.columns:\n",
    "            data[col] = data[col].astype(int)\n",
    "            \n",
    "    return data\n",
    "\n",
    "# --- CHARGEMENT DES DONNÉES ---\n",
    "try:\n",
    "    df = load_and_clean_data('ab_data.csv')\n",
    "except FileNotFoundError:\n",
    "    st.error(\"Erreur : Le fichier de données 'votre_fichier.csv' n'a pas été trouvé. Assurez-vous qu'il se trouve dans le même dossier que le script.\")\n",
    "    st.stop()\n",
    "\n",
    "\n",
    "# --- BARRE LATÉRALE POUR LES FILTRES ---\n",
    "st.sidebar.header(\"Filtres Interactifs\")\n",
    "\n",
    "# Filtre par Campagne\n",
    "selected_campaign = st.sidebar.multiselect(\n",
    "    'Sélectionner la Campagne',\n",
    "    options=df['Campaign name'].unique(),\n",
    "    default=df['Campaign name'].unique()\n",
    ")\n",
    "\n",
    "# Filtre par Ensemble de Publicités\n",
    "selected_ad_set = st.sidebar.multiselect(\n",
    "    'Sélectionner l\\'Ensemble de Publicités',\n",
    "    options=df['Ad Set Name'].unique(),\n",
    "    default=df['Ad Set Name'].unique()\n",
    ")\n",
    "\n",
    "# Filtre par Genre\n",
    "selected_gender = st.sidebar.multiselect(\n",
    "    'Sélectionner le Genre',\n",
    "    options=df['Gender'].unique(),\n",
    "    default=df['Gender'].unique()\n",
    ")\n",
    "\n",
    "# Filtre par Âge\n",
    "selected_age = st.sidebar.multiselect(\n",
    "    'Sélectionner la Tranche d\\'Âge',\n",
    "    options=df['Age'].unique(),\n",
    "    default=df['Age'].unique()\n",
    ")\n",
    "\n",
    "# Filtre par Date\n",
    "min_date = df['Day'].min()\n",
    "max_date = df['Day'].max()\n",
    "selected_date_range = st.sidebar.date_input(\n",
    "    'Sélectionner une plage de dates',\n",
    "    [min_date, max_date],\n",
    "    min_value=min_date,\n",
    "    max_value=max_date\n",
    ")\n",
    "\n",
    "# --- APPLICATION DES FILTRES ---\n",
    "df_filtered = df[\n",
    "    df['Campaign name'].isin(selected_campaign) &\n",
    "    df['Ad Set Name'].isin(selected_ad_set) &\n",
    "    df['Gender'].isin(selected_gender) &\n",
    "    df['Age'].isin(selected_age) &\n",
    "    (df['Day'] >= pd.to_datetime(selected_date_range[0])) &\n",
    "    (df['Day'] <= pd.to_datetime(selected_date_range[1]))\n",
    "]\n",
    "\n",
    "if df_filtered.empty:\n",
    "    st.warning(\"Aucune donnée disponible pour les filtres sélectionnés.\")\n",
    "    st.stop()\n",
    "\n",
    "# --- AFFICHAGE DU DASHBOARD ---\n",
    "st.title(\"📊 Dashboard d'Analyse des Performances Marketing\")\n",
    "st.markdown(\"Utilisez les filtres dans la barre latérale pour explorer les données.\")\n",
    "\n",
    "\n",
    "# --- KPIs PRINCIPAUX ---\n",
    "st.header(\"Vue d'Ensemble des Performances\")\n",
    "\n",
    "total_spent = df_filtered['Amount spent (USD)'].sum()\n",
    "total_impressions = df_filtered['Impressions'].sum()\n",
    "total_link_clicks = df_filtered['Link clicks'].sum()\n",
    "\n",
    "# Calculs sécurisés pour éviter la division par zéro\n",
    "cpc = total_spent / total_link_clicks if total_link_clicks > 0 else 0\n",
    "ctr = (total_link_clicks / total_impressions) * 100 if total_impressions > 0 else 0\n",
    "cpm = (total_spent / total_impressions) * 1000 if total_impressions > 0 else 0\n",
    "\n",
    "col1, col2, col3, col4 = st.columns(4)\n",
    "col1.metric(\"Montant Dépensé (USD)\", f\"${total_spent:,.2f}\")\n",
    "col2.metric(\"Clics sur le lien\", f\"{total_link_clicks:,}\")\n",
    "col3.metric(\"CPC Moyen\", f\"${cpc:,.2f}\")\n",
    "col4.metric(\"CTR Moyen\", f\"{ctr:,.2f}%\")\n",
    "\n",
    "\n",
    "# --- GRAPHIQUES ---\n",
    "st.header(\"Analyse Détaillée\")\n",
    "\n",
    "# 1. Analyse Temporelle\n",
    "daily_performance = df_filtered.groupby('Day').agg({'Amount spent (USD)': 'sum', 'Link clicks': 'sum'}).reset_index()\n",
    "fig_temporal = px.line(daily_performance, x='Day', y=['Amount spent (USD)', 'Link clicks'], \n",
    "                       title=\"Évolution Journalière des Dépenses et des Clics\",\n",
    "                       labels={'value': 'Valeur', 'variable': 'Métrique'},\n",
    "                       markers=True)\n",
    "fig_temporal.update_layout(yaxis_title=None)\n",
    "st.plotly_chart(fig_temporal, use_container_width=True)\n",
    "\n",
    "\n",
    "# 2. Analyse par Ensemble de Publicités\n",
    "col_perf, col_budget = st.columns(2)\n",
    "\n",
    "with col_perf:\n",
    "    st.subheader(\"Performance par Ensemble de Publicités\")\n",
    "    ad_set_perf = df_filtered.groupby('Ad Set Name').agg({\n",
    "        'Amount spent (USD)': 'sum',\n",
    "        'Link clicks': 'sum',\n",
    "        'Impressions': 'sum'\n",
    "    }).reset_index()\n",
    "    ad_set_perf['CPC'] = ad_set_perf['Amount spent (USD)'] / ad_set_perf['Link clicks']\n",
    "    ad_set_perf['CTR'] = (ad_set_perf['Link clicks'] / ad_set_perf['Impressions']) * 100\n",
    "    ad_set_perf.fillna(0, inplace=True)\n",
    "    \n",
    "    fig_ad_set_cpc = px.bar(ad_set_perf.sort_values('CPC'), x='CPC', y='Ad Set Name', \n",
    "                            orientation='h', title=\"CPC par Ensemble de Publicités\",\n",
    "                            color='CPC', color_continuous_scale='Reds')\n",
    "    st.plotly_chart(fig_ad_set_cpc, use_container_width=True)\n",
    "\n",
    "with col_budget:\n",
    "    st.subheader(\"Répartition du Budget\")\n",
    "    fig_ad_set_budget = px.pie(ad_set_perf, names='Ad Set Name', values='Amount spent (USD)',\n",
    "                               title=\"Répartition des Dépenses par Ensemble de Publicités\")\n",
    "    st.plotly_chart(fig_ad_set_budget, use_container_width=True)\n",
    "\n",
    "\n",
    "# --- VUE DES DONNÉES BRUTES ---\n",
    "with st.expander(\"Voir les données filtrées\"):\n",
    "    st.dataframe(df_filtered)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
